export function overlayHtml() {
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'"><style>
  :root{color-scheme:light;font-family:Inter,-apple-system,sans-serif}*{box-sizing:border-box}body{margin:0;background:transparent;overflow:hidden;pointer-events:none}.wrap{height:100vh;display:flex;flex-direction:column;justify-content:flex-end;gap:8px;padding:8px}.toasts{align-self:flex-end;display:grid;gap:6px;max-width:330px}.toast{background:rgba(23,43,77,.94);border:1px solid rgba(255,255,255,.2);border-radius:10px;color:white;font-size:12px;padding:9px 12px;box-shadow:0 6px 20px #091e4233}.lane{align-self:flex-end;display:flex;align-items:flex-end;gap:7px;background:rgba(255,255,255,.82);border:1px solid #dfe1e6;border-radius:18px;padding:8px 10px;box-shadow:0 8px 24px #091e4222}.dog{position:relative;width:62px;text-align:center;transform-origin:50% 100%;animation:bob var(--duration) ease-in-out infinite}.dog.static{animation:none}.sprite{height:44px;filter:drop-shadow(0 2px 2px #0002)}.sprite svg{height:44px;width:44px}.badge{display:block;color:#172b4d;font-size:9px;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.state{font-size:8px;color:#5e6c84}.overflow{font-weight:800;color:#172b4d;padding:12px 4px}@keyframes bob{50%{transform:translateY(-5px) translateX(var(--drift))}}@media(prefers-reduced-motion:reduce){.dog{animation:none!important}}
  </style></head><body><div class="wrap"><div class="toasts" id="toasts"></div><div class="lane" id="lane"></div></div><script>
  const dog=(coat,muzzle,ears)=>'<svg viewBox="0 0 64 64" aria-hidden="true"><path fill="'+coat+'" d="'+ears+' C55 30 54 57 32 57S9 30 14 25Z"/><ellipse fill="'+muzzle+'" cx="32" cy="42" rx="17" ry="12"/><circle cx="24" cy="31" r="2.5"/><circle cx="40" cy="31" r="2.5"/><circle cx="32" cy="41" r="3.5"/><path d="M26 48q6 5 12 0" fill="none" stroke="#35261f" stroke-width="2"/></svg>';
  const icons={shiba:dog('#d97832','#fff0d2','M13 27 10 7l17 14h10L54 7l-3 20'),retriever:dog('#e7b85d','#f8daa0','M14 27C6 9 2 18 9 34h46c7-16 3-25-5-7'),collie:dog('#292c33','#fff','M13 27 16 6l14 15h4L48 6l3 21'),poodle:dog('#eee4dc','#fff','M12 28C3 14 16 8 23 19c5-9 13-9 18 0 7-11 20-5 11 9'),corgi:dog('#c96f31','#fff4df','M12 27 11 5l18 16h6L53 5l-1 22')};
  window.renderHarnessOverlay=(state)=>{const lane=document.getElementById('lane'),toasts=document.getElementById('toasts');toasts.replaceChildren(...state.toasts.map(t=>{const n=document.createElement('div');n.className='toast';n.textContent=t.message;return n}));lane.replaceChildren(...state.dogs.map(d=>{const n=document.createElement('div');n.className='dog'+(state.reducedMotion?' static':'');n.style.setProperty('--duration',(1000/Math.max(1,d.fps))+'ms');n.style.setProperty('--drift',(d.velocity/8)+'px');const elapsed=d.startedAt?Math.max(0,Math.floor((Date.now()-Date.parse(d.startedAt))/1000))+'s elapsed':null;n.title=[d.agentName,d.projectName,d.taskTitle,d.phase,d.state,elapsed,d.changedFiles+' changed files',d.pendingInteraction?'interaction pending':null].filter(Boolean).join(' · ');const icon=document.createElement('div');icon.className='sprite';icon.innerHTML=icons[d.dogId]||icons.shiba;const name=document.createElement('span');name.className='badge';name.textContent=d.agentName+(d.activeRuns>1?' ×'+d.activeRuns:'');const phase=document.createElement('span');phase.className='state';phase.textContent=d.phase+' · '+d.state;n.append(icon,name,phase);return n}),...(state.overflow?[Object.assign(document.createElement('span'),{className:'overflow',textContent:'+'+state.overflow})]:[]));document.body.style.display=state.hidden?'none':''};
  </script></body></html>`;
}
